name: kiosk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.6.0+63

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_card: ^1.1.7
  awesome_notifications: ^0.6.21
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.3.0
  country_list_pick: ^1.0.1+5
  country_picker: ^2.0.13
  cupertino_icons: ^1.0.2
  currency_picker: ^2.0.16
  currency_text_input_formatter: ^2.1.5
  device_info_plus: ^9.1.0
  easy_localization: ^3.0.0
  equatable: 2.0.5
  faker: ^2.1.0
  firebase_analytics: ^9.3.8
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.9.0
  firebase_messaging: ^11.2.7
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^1.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: 9.3.2
  flutter_material_pickers: ^3.1.2
  flutter_native_splash: ^2.0.5
  flutter_pdfview: ^1.3.0
  flutter_screenutil: ^5.8.3
  flutter_secure_storage: ^6.0.0
  flutter_share: ^2.0.0
  flutter_slidable: ^1.2.0
  flutter_spinkit: ^5.1.0
  fluttericon: ^2.0.0
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  group_button: ^4.7.0
  hive_flutter: ^1.1.0
  http: ^1.1.0
  huawei_iap: ^6.4.0+302
  image_picker: ^0.8.7+5
  in_app_purchase: ^3.1.5
  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.3+1
  introduction_screen: ^3.0.2
  local_auth: ^2.1.2
  logger: ^1.3.0
  material_design_icons_flutter: ^5.0.6996
  modal_bottom_sheet: ^3.0.0-pre
  nice_intro: ^0.2.1
  package_info_plus: ^4.1.0
  path_provider: ^2.0.8
  pdf: ^3.10.1
  permission_handler: ^10.1.0
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  recase: 4.0.0
  showcaseview: ^2.0.0+1
  signature: ^5.4.0
  sizedbox_extention: ^0.0.2
  store_redirect: ^2.0.1
  string_validator: ^0.3.0
  sunmi_printer_plus: ^2.1.01
  survey_kit: ^0.1.2
  syncfusion_flutter_charts: ^22.2.5
  tuple: ^2.0.1
  url_launcher: ^6.1.2
  validators: ^3.0.0
  youtube_player_flutter: ^8.0.0

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  barcode: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^6.1.0
  http: 1.1.0
  flutter_pdfview: 1.2.9


dev_dependencies:
  build_runner: ^2.1.11
  # flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kroonKiosk.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#f8c21a"
  color_dark: "#f8c21a"
  image: "assets/images/splashIcon.png"

  fullscreen: true
